// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkwoiuprgmroewtksqdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrd29pdXByZ21yb2V3dGtzcWRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NDYxNTYsImV4cCI6MjA3MjEyMjE1Nn0.U7YjpX0lKGj9IdPDXr3vD27xOjp4uE7J0HsYVDv-BvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});